config/routes.rb
Rails.application.routes.draw do

  resources :attachments, only: [:index, :new, :create]

  resources :documents, only: [:index, :new, :create, :destroy]
  root "attachments#index"
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates_presence_of :attachment
	before_save :update_file_attributes

  private

  def update_file_attributes
    if attachment.present? && attachment_changed?
      self.content_type = attachment.file.content_type
      self.original_filename = attachment.file.original_filename
    end
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
    validates_presence_of :attachment, :name	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def index
    # @attachments = Attachment.all.order(created_at: :desc)  
    @attachments = Attachment.all.sort_by { |obj| obj.created_at }
    
  end

  def new
    @attachment = Attachment.new
  end

  def create
    @attachment = Attachment.new(attachments_params)
    @attachment.data_type = params[:data_type]
    if @attachment.save
      @attachment.update_attribute(:location, @attachment.attachment.url)
      redirect_to attachments_path, notice: "The file #{@attachment.original_filename} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy
    redirect_to attachments_path, notice:  "The file #{@attachment.original_filename} has been deleted."
  end

private
  def attachments_params
    params.fetch(:attachment, {}).permit(:attachment, :data_type)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  protect_from_forgery
  def index
    @documents = Document.all
    @document = Document.new
  end

  def new
    @document = Document.new
  end

  def create
  	  # byebug
       
      @document = Document.new(document_params)
     # @document.save
      

      respond_to do |format|
      if @document.save
         flash[:notice] = "Comment successfully created"
        format.html { redirect_to documents_path, notice: 'File was successfully created.' }
        format.js   { flash.now[:notice] = "Here is my flash notice" }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
        format.js   { }
      end


end
      
    # if @document.save
    #   redirect_to documents_path, notice: "The document #{@document.name} has been uploaded."
    # else
    #   render "new"
    # end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_path, notice:  "The document #{@document.name} has been deleted."
  end

private
  def document_params

     params.fetch(:document, {}).permit(:attachment, :name)
    # params.require(:document).permit(:name, :attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/attachments/create.html.erb
<h1>Attachments#create</h1>
<p>Find me in app/views/attachments/create.html.erb</p>

app/views/attachments/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>

<br />
<%= link_to "Upload New File", new_attachment_path, class: "btn btn-primary" %>
<br />
<br />
<table id="data" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>File name</th>
      <th>Data type</th>     
      <th>File Location</th>
      <th>Content type</th>
    </tr>
  </thead>
  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.original_filename %></td> 
         <td><%= attachment.data_type %></td> 
         <td><%= attachment.location %></td> 
         <td><%= attachment.content_type %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/attachments/new.html.erb
<% if !@attachment.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @attachment, :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group">
    <%= f.label :data_type, "Select Data Type:", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= select_tag "data_type", options_for_select(AppConfig.data_types), :class => "btn btn-default dropdown-toggle" %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :attachment, "Upload File:", class: "col-md-4 control-label" %>
      <div class="col-md-5">
        <div class="input-group">
          <span class="input-group-btn">
            <span class="btn btn-primary" onclick="$(this).parent().find('input[type=file]').click();">Browse</span>
                  Upload File: <%= f.file_field :attachment, :onchange => "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\|/]/).pop());", :style => "display: none;" %>
          </span>
          <span class="form-control"></span>
        </div>
      </div>
    </div>

  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
       <%= f.submit "Submit", class: "btn btn-info btn-primary" %>  
    </div>
  </div>
 <% end %>

app/views/documents/_form.html.erb
<div class="well">

  <% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>

<div class="something"></div>

<% if !@document.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

   <%#= AppConfig.data_types %>

  <%#= form_for @document, html: { multipart: true } do |f| %>

    <%#= form_for(:document, :url => {:controller => "documents", :action => "create", :format => "js"}, :html => {:class => "form-horizontal"}, :remote => true) do |f| %>

    <%= form_for(@document, :remote => true, :html => {multipart: true  }) do |f| %>
<%#= form_for @document, :remote => true, :html => {multipart: true  } do |f| %>

  <%= select_tag "data_type", options_for_select(AppConfig.data_types) %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%#= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/documents/_index_data.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <!-- <th>Download Link</th> -->
      <th>Document Location</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>

    <% @documents.each do |document| %>
    <%# byebug %>
      <tr>
        <td><%= document.name %></td>
        <!-- <td><%#= link_to "Download Document", document.attachment_url %></td>  -->
        <!-- <td><%#= document.attachment_url %></td> -->
        <td><%= document.attachment.url %></td>
        <!-- <td><%#= request.host + document.attachment_url %></td> -->
        <td><%= button_to "Delete",  document, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{document.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/create.js.erb
<% if @document.persisted? %>
    $('#index_data_div').html("<%= escape_javascript(render 'index_data') %>");
    // $('.something').text(<%= flash[:notice] %> )
    alert('hhhhhhhhhhhh');
<% else %>
    $('#my_form_div').html("<%= escape_javascript(render 'form') %>");

<% end %>

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>

<div class="something"></div>

<div id ='my_form_div'>
  <%= render 'form' %>
</div>





<br />
<%#= link_to "New Document", new_document_path, class: "btn btn-primary" %>
<br />
<br />

<div id ='index_data_div'>
   <%= render "index_data" %>
</div>

app/views/documents/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarrierWaveExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!-- // <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> -->
<!-- <script src=""></script> -->
<!-- <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script> -->


  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->

  <!-- <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css"> -->
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container" style="padding-top:20px;">
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>

<%= yield %>


</div>


</body>
</html>